local dof = require("dof.dof")
local light_and_shadows = require "light_and_shadows.light_and_shadows"


function init(self)
	msg.post(".", "acquire_input_focus")
	--light_and_shadows.upscale = true
	local far_z = camera.get_far_z(msg.url("/game_camera#camera"))
	local near_z = camera.get_near_z(msg.url("/game_camera#camera"))
	dof.set_camera_params(near_z, far_z)
	dof.set_distance(1.0, 4.0)
	dof.set_focus(0.5, 0.5)
	dof.set_dof_mode(0)
	dof.set_gaussian_blur(3, 5)
end

function update(self, dt)

end

function fixed_update(self, dt)

end

function on_input(self, action_id, action)

end
