-- FROM: https://defold.com/examples/render/orbit_camera/

-- The initial zoom level
go.property("zoom", 3)
-- The speed of the zoom
go.property("zoom_speed", 0.01)
-- The speed of the rotation
go.property("rotation_speed", 0.5)
-- The offset of the camera from the origin
go.property("offset", vmath.vector3(0, 0, 0))

local data = require "tiny-city.scripts.lib.data"
local const = require "tiny-city.scripts.lib.const"

local defaults = {}

function init(self)
	--msg.post(".", "acquire_input_focus")

	-- Initialize start values
	self.yaw = go.get(".", "euler.y")
	self.pitch = go.get(".", "euler.x")
	self.zoom_offset = 0
	self.current_yaw = self.yaw
	self.current_pitch = self.pitch
	self.current_zoom = self.zoom_offset
	data.camera_zoom = self.zoom

	defaults.yaw = go.get(".", "euler.y")
	defaults.pitch = go.get(".", "euler.x")
	defaults.zoom_offset = 0
	defaults.current_yaw = self.yaw
	defaults.current_pitch = self.pitch
	defaults.current_zoom = self.zoom_offset
	defaults.camera_zoom = self.zoom

	self.camera_zoom = self.zoom
	self.pitch_up = true
	self.is_moving = true
end

function update(self, dt)
	if self.is_moving then
		-- zoom
		if self.camera_zoom > 15 then
			self.zoom_offset = self.zoom_offset - 9 * dt
		else
			self.is_moving = false
		end

		local raw_pitch = self.pitch

		if raw_pitch > -30 and self.pitch_up then
			raw_pitch = raw_pitch - 12 * dt
		elseif raw_pitch < -20 then
			self.pitch_up = false
			raw_pitch = raw_pitch + 12 * dt
		end

		self.pitch = vmath.lerp(0.2, self.pitch, raw_pitch)
	end

	-- Animate camera rotation and zoom
	self.current_yaw = vmath.lerp(0.15, self.current_yaw, self.yaw)
	self.current_pitch = vmath.lerp(0.15, self.current_pitch, self.pitch)
	self.current_zoom = vmath.lerp(0.15, self.current_zoom, self.zoom_offset)
	self.camera_zoom = self.zoom + self.current_zoom

	-- Calculate rotation and position
	local camera_yaw = vmath.quat_rotation_y(math.rad(self.current_yaw))
	local camera_pitch = vmath.quat_rotation_x(math.rad(self.current_pitch))
	local camera_rotation = camera_yaw * camera_pitch
	local camera_position = self.offset + vmath.rotate(camera_rotation, vmath.vector3(0, 0, self.zoom + self.current_zoom))

	-- Set camera position and rotation
	go.set_position(camera_position)
	go.set_rotation(camera_rotation)
end

function on_input(self, action_id, action)
	if action_id == const.TRIGGERS.MOUSE_BUTTON_RIGHT and not action.pressed then
		self.yaw   = self.yaw - action.dx * self.rotation_speed
		self.pitch = self.pitch + action.dy * self.rotation_speed
	elseif action_id == const.TRIGGERS.MOUSE_WHEEL_UP then
		self.zoom_offset = self.zoom_offset - self.zoom * self.zoom_speed
	elseif action_id == const.TRIGGERS.MOUSE_WHEEL_DOWN then
		self.zoom_offset = self.zoom_offset + self.zoom * self.zoom_speed
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("reset") then
		self.yaw = defaults.yaw
		self.pitch = defaults.pitch
		self.zoom_offset = defaults.zoom_offset
		self.current_yaw = defaults.current_yaw
		self.current_pitch = defaults.current_pitch
		self.current_zoom = defaults.current_zoom
		data.camera_zoom = defaults.camera_zoom
	end

	if message_id == hash("enable_input") then
		msg.post(".", "acquire_input_focus")
	elseif message_id == hash("disable_input") then
		msg.post(".", "release_input_focus")
	end
end
