local game_manager     = require("tiny-city.scripts.game.manager")
local pathfinder_debug = require("tiny-city.scripts.lib.pathfinder_debug")

function init(self)
	msg.post(".", "acquire_input_focus")

	--	msg.post("/camera#camera", "disable")
	--	msg.post("/game_camera#camera", "enable")


	profiler.enable_ui(true)
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)

	game_manager.init()

	particlefx.play("/chimney-large#smoke")
	particlefx.play("/chimney-large1#smoke")
end

function update(self, dt)
	game_manager.update(dt)

	--pathfinder_debug.draw_edges()
end

function on_input(self, action_id, action)
	game_manager.input(action_id, action)
end
