local M = {}

local template = [[embedded_components {
    id: "model"
    type: "model"
    data: "mesh: \"/assets/models/%s/%s.glb\"\n"
    "name: \"\"\n"
    "materials {\n"
    "  name: \"colormap\"\n"
    "  material: \"/materials/model_unlit_instanced.material\"\n"
    "  textures {\n"
    "    sampler: \"tex0\"\n"
    "    texture: \"/assets/models/%s/Textures/colormap.png\"\n"
    "  }\n"
    "}\n"
    "create_go_bones: false\n"
    ""
}
]]

local function get_models(path)
    local folder = path:match("([^/]+)/?$")
    -- select and clear the directory for generated assets
    local root_dir = "/assets/models/gen/" .. folder
    editor.delete_directory(root_dir)
    -- list all assets from the asset pack
    local assets = editor.get(path, "children")
    return folder, root_dir, assets
end

local function create_go(folder, root_dir, assets)
    local resources = {}
    for i = 1, #assets do
        local glb_path = assets[i]
        local base_name = glb_path:match("([^/]+)%.glb$")
        if base_name then
            local go = root_dir .. "/" .. base_name .. ".go"
            resources[#resources+1] = {go, template:format(folder, base_name, folder)}
        end
    end
    editor.create_resources(resources)
    return resources
end

local function create_collection(folder, root_dir, resources)
    local collection = "/assets/models/gen/" .. folder .. ".collection"
    -- txs array, start by clearing the collections, so we don't add 
    -- too many items when re-generating the assets
    local edit_txs = { editor.tx.clear(collection, "children") }

    local row = math.floor(math.sqrt(#resources))
    local half = math.floor(row / 2)
    for i = 1, #resources do
        local go = resources[i][1]
        local x = (i - 1) % row
        local z = math.floor(i/row)
        edit_txs[#edit_txs+1] = editor.tx.add(collection, "children", {
            type = "go-reference",
            path = go,
            -- position all objects around 0,0
            position = {- (x - half) * 1.5, 0, - (z - half) * 1.5},
            children = {
                {
                    -- no id necessary, it's auto-generted when omitted
                    type = "go",
                    scale = {0.007, 0.007, 0.007},
                    position = {0, 0.2, 0.7},
                    components = {
                        {
                            type = "label",
                            text = go:match("([^/]+)%.go$"),
                            font = "/builtins/fonts/default.font",
                            material = "/builtins/fonts/label.material"
                        }
                    }
                }
            }
        })
    end
    editor.transact(edit_txs)
    -- we don't care about undo here, might as well save:
    editor.save()
end

function M.get_commands()
    -- Add editor commands
    -- Learn more: https://defold.com/manuals/editor-scripts/#commands
    -- Remove this function if not needed
    return {
        editor.command({
            label = "Generate models",
            locations = {"Assets"},
            id = "app.edit.generate-models",
            query = {
                selection = {type = "resource", cardinality = "one"}
            },
            run = function(opts)
                local path = editor.get(opts.selection, "path")
                local folder, root_dir, assets = get_models(path)
                local resources = create_go(folder, root_dir, assets)
                create_collection(folder, root_dir, resources)
            end
        })
    }
end

return M
