embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/clouds/cloud_3.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/tiny-city/components/materials/noshadow/model_instanced_noshadow.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/generic/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
