embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/birds.glb\"\n"
  "skeleton: \"/tiny-city/assets/models/birds.glb\"\n"
  "animations: \"/tiny-city/assets/models/birds.glb\"\n"
  "default_animation: \"Armature|Scene\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.001\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"Material.002\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
embedded_components {
  id: "model1"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/birds.glb\"\n"
  "skeleton: \"/tiny-city/assets/models/birds.glb\"\n"
  "animations: \"/tiny-city/assets/models/birds.glb\"\n"
  "default_animation: \"Armature.001|Scene\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.001\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"Material.002\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
  position {
    x: 0.279218
    z: 0.392401
  }
}
embedded_components {
  id: "model2"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/birds.glb\"\n"
  "skeleton: \"/tiny-city/assets/models/birds.glb\"\n"
  "animations: \"/tiny-city/assets/models/birds.glb\"\n"
  "default_animation: \"Armature.002|Scene\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.001\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"Material.002\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
  position {
    x: -0.417151
    z: 0.478868
  }
}
embedded_components {
  id: "model3"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/birds.glb\"\n"
  "skeleton: \"/tiny-city/assets/models/birds.glb\"\n"
  "animations: \"/tiny-city/assets/models/birds.glb\"\n"
  "default_animation: \"Armature.003|Scene\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.001\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"Material.002\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
  position {
    x: 0.3969
    z: 0.824751
  }
}
embedded_components {
  id: "model4"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/birds.glb\"\n"
  "skeleton: \"/tiny-city/assets/models/birds.glb\"\n"
  "animations: \"/tiny-city/assets/models/birds.glb\"\n"
  "default_animation: \"Armature.004|Scene\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material.001\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"Material.002\"\n"
  "  material: \"/light_and_shadows/materials/model/skinned/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/white.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
  position {
    x: -0.21539
    z: 0.937119
  }
}
