embedded_components {
  id: "island_bottom"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/island_base.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/kenney_cars_colormap.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
embedded_components {
  id: "island_top"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/island_top.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced_nocast.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/kenney_cars_colormap.png\"\n"
  "  }\n"
  "}\n"
  ""
}
