embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/graph_editor/assets/models/node.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"default\"\n"
  "  material: \"/tiny-city/components/materials/node.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/generic/white.png\"\n"
  "  }\n"
  "}\n"
  ""
}
