embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/tiny-city/assets/models/town/fountain-square-detail.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Water\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/kenny_town_colormap.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"colormap\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/tiny-city/assets/textures/kenny_town_colormap.png\"\n"
  "  }\n"
  "}\n"
  "create_go_bones: false\n"
  ""
}
