embedded_components {
    id: "model"
    type: "model"
    data: "mesh: \"/tiny-city/assets/models/commercial/low-detail-building-e.glb\"\n"
    "name: \"\"\n"
    "materials {\n"
    "  name: \"colormap\"\n"
    "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
    "  textures {\n"
    "    sampler: \"tex0\"\n"
    "    texture: \"/tiny-city/assets/textures/kennny_commercial_colormap.png\"\n"
    "  }\n"
    "}\n"
    "create_go_bones: false\n"
    ""
}
